version: 2

models:
  - name: int_daily_transactions
    description: Daily aggregated transactions by store
    columns:
      - name: date_day
        description: Date of transactions (YYYY-MM-DD)
        tests:
          - not_null
      - name: store_id
        description: Foreign key to stores table
        tests:
          - not_null
          - relationships:
              to: ref('stg_stores')
              field: store_id
      - name: daily_transactions_count
        description: Number of transactions for the day
        tests:
          - not_null
          - positive_values
      - name: daily_amount_total
        description: Total transaction amount for the day
        tests:
          - not_null
      - name: avg_transaction_amount
        description: Average transaction amount for the day
        tests:
          - not_null 