version: 2

models:
  - name: fct_transactions
    description: Core transaction facts with store dimensions
    columns:
      - name: transaction_id
        description: Unique identifier for each transaction
        tests:
          - unique
          - not_null
      - name: store_id
        description: Foreign key to stores table
        tests:
          - not_null
          - relationships:
              to: ref('stg_stores')
              field: store_id
      - name: transaction_date
        description: Date of the transaction
        tests:
          - not_null
      - name: transaction_amount
        description: Amount of the transaction in USD
        tests:
          - not_null
      - name: store_name
        description: Name of the store
        tests:
          - not_null
      - name: store_location
        description: Location of the store
        tests:
          - not_null 