version: 2

sources:
  - name: crm
    database: enterprise_analytics
    schema: crm_raw
    tables:
      - name: stores
        description: Raw store data
        columns:
          - name: id
            description: Primary key
            data_tests:
              - unique
              - not_null
          - name: name
            description: Name of the store
            data_tests:
              - not_null
          - name: address
            description: Store address
          - name: city
            description: Store city
            data_tests:
              - not_null
          - name: country
            description: Store country
            data_tests:
              - not_null
          - name: created_at
            description: Store creation timestamp
            data_tests:
              - not_null
          - name: typology
            description: Store typology/type
            data_tests:
              - not_null
          - name: customer_id
            description: ID of the customer who owns the store
            data_tests:
              - not_null

      - name: transactions
        description: Raw transaction data
        columns:
          - name: id
            description: Primary key
            data_tests:
              - unique
              - not_null
          - name: device_id
            description: Foreign key to devices
            data_tests:
              - not_null
              - relationships:
                  to: ref('stg_devices')
                  field: device_id
          - name: product_name
            description: Name of the product
            data_tests:
              - not_null
          - name: product_sku
            description: Stock keeping unit (unique product identifier)
            data_tests:
              - not_null
          - name: category_name
            description: Product category name
            data_tests:
              - not_null
          - name: amount
            description: Transaction amount in USD
            data_tests:
              - not_null
          - name: status
            description: Transaction status
            data_tests:
              - not_null
          - name: card_number
            description: Payment card number
            data_tests:
              - not_null
          - name: cvv
            description: Card verification value
            data_tests:
              - not_null
          - name: created_at
            description: Record creation timestamp
            data_tests:
              - not_null
          - name: happened_at
            description: Transaction timestamp
            data_tests:
              - not_null

      - name: devices
        description: Raw device data
        columns:
          - name: id
            description: Primary key
            data_tests:
              - unique
              - not_null
          - name: store_id
            description: Foreign key to stores
            data_tests:
              - not_null
              - relationships:
                  to: source('crm', 'stores')
                  field: id
          - name: type
            description: Type of device
            data_tests:
              - not_null

models:
  - name: stg_stores
    description: Cleaned store data
    columns:
      - name: store_id
        description: Unique identifier for each store
        data_tests:
          - unique
          - not_null
      - name: store_name
        description: Name of the store
        data_tests:
          - not_null
      - name: address
        description: Store address
      - name: city
        description: Store city
        data_tests:
          - not_null
      - name: country
        description: Store country
        data_tests:
          - not_null
      - name: typology
        description: Store typology/type
        data_tests:
          - not_null
      - name: customer_id
        description: ID of the customer who owns the store
        data_tests:
          - not_null
      - name: created_at
        description: Store creation timestamp
        data_tests:
          - not_null

  - name: stg_transactions
    description: Cleaned transaction data
    columns:
      - name: transaction_id
        description: Unique identifier for each transaction
        data_tests:
          - unique
          - not_null
      - name: device_id
        description: Foreign key to devices table
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_devices')
              field: device_id
      - name: product_name
        description: Name of the product
        data_tests:
          - not_null
      - name: product_sku
        description: Stock keeping unit (unique product identifier)
        data_tests:
          - not_null
      - name: category_name
        description: Product category name
        data_tests:
          - not_null
      - name: amount
        description: Transaction amount in USD
        data_tests:
          - not_null
      - name: status
        description: Transaction status
        data_tests:
          - not_null
      - name: timestamp
        description: Transaction timestamp
        data_tests:
          - not_null
      - name: created_at
        description: Record creation timestamp
        data_tests:
          - not_null 